ChartValues:
  replicaCount: 1
  service:
    port: 8080
    type: LoadBalancer
HelmChartPath: Chart
RuntimeType: Kubernetes
OutputCmd: |-
  export SERVICE_IP=$(kubectl get svc --namespace ${Namespace} spring-boot-chart -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
  echo "http://$SERVICE_IP/"
ServiceType: private
ArtifactSourceType: HelmChart
ServiceBuildRegion: ap-southeast-1
RepoName: yehanyh/spring-boot-chart
RegionId: cn-hangzhou
OutputType: OutputCommand
Owner: yehanyh
Branch: main
Platform: github
