ChartValues:
  replicaCount: ${ReplicaCount}
  service:
    port: 8080
    type: LoadBalancer
HelmChartPath: Chart
OutputCmd: |
  export SERVICE_IP=$(kubectl get svc --namespace ${Namespace} ${ReleaseName} -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
  echo "Visit URL: http://$SERVICE_IP:8080/"
ServiceType: private
ArtifactSourceType: HelmChart
ServiceBuildRegion: ap-southeast-1
RepoName: yehanyh/spring-boot-chart
RegionId: cn-hangzhou
CustomParameters:
- NoEcho: false
  Type: Number
  AllowedPattern: ''
  Label: Pod副本数
  ConstraintDescription: ''
  Default: '1'
  Name: ReplicaCount
OutputType: OutputCommend
Owner: yehanyh
Branch: main
Platform: github
