ChartValues:
  replicaCount: 1
  service:
    port: 8080
    type: LoadBalancer
HelmChartPath: Chart
ServiceType: private
ArtifactSourceType: HelmChart
ServiceBuildRegion: ap-southeast-1
RepoName: yehanyh/spring-boot-chart
RegionId: cn-hangzhou
OutputType: HelmNotes
Owner: yehanyh
Branch: main
Platform: github
