ChartValues:
  replicaCount:
    Ref: ReplicaCount
  service:
    port: 8080
    type: LoadBalancer
HelmChartPath: Chart
RuntimeType: Kubernetes
ServiceType: private
ArtifactSourceType: HelmChart
ServiceBuildRegion: ap-southeast-1
RepoName: CheYuX/spring-boot-chart-test
RegionId: cn-hangzhou
CustomParameters:
- NoEcho: false
  Type: Number
  AllowedPattern: ''
  Label: Pod数
  ConstraintDescription: ''
  Default: '1'
  Name: ReplicaCount
OutputType: HelmNotes
Owner: CheYuX
Branch: main
Platform: github
